import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: any;
  params: any;
}) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <div className="max-w-6xl mx-auto">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
